export const CAT_STYLES = {
  sleeping:    { fill: '#243121', stroke: '#3e5236' },
  bathroom:    { fill: '#1f2a30', stroke: '#34464f' },
  work:        { fill: '#2a2435', stroke: '#4a3f6a' },
  social:      { fill: '#3a2f1a', stroke: '#5a4a28' },
  outdoor:     { fill: '#27321f', stroke: '#3e4f30' },
  transition:  { fill: '#252830', stroke: '#3a4050' },
  circulation: { fill: '#2a2418', stroke: '#4a3c24' },
  service:     { fill: '#3f2c18', stroke: '#6a4a26' },
  furniture:   { fill: '#282420', stroke: '#4a3e30' },
};

const defs = [
  // sleeping
  { defId: 'master_suite',    label: 'Master Suite',    w: 4.0, d: 5.0, category: 'sleeping' },
  { defId: 'bed_ensuite',     label: 'Bed+Ensuite',     w: 4.0, d: 4.5, category: 'sleeping' },
  { defId: 'bedroom_dbl',     label: 'Bedroom Dbl',     w: 3.4, d: 4.0, category: 'sleeping' },
  { defId: 'bedroom_sgl',     label: 'Bedroom Sgl',     w: 2.7, d: 3.2, category: 'sleeping' },
  { defId: 'guest_suite',     label: 'Guest Suite',     w: 3.5, d: 4.5, category: 'sleeping' },
  // bathroom
  { defId: 'ensuite_full',    label: 'Ensuite Full',    w: 1.8, d: 2.8, category: 'bathroom' },
  { defId: 'ensuite_compact', label: 'Ensuite Compact', w: 1.5, d: 2.1, category: 'bathroom' },
  { defId: 'bathroom',        label: 'Bathroom',        w: 2.0, d: 2.5, category: 'bathroom' },
  { defId: 'wc_powder',       label: 'WC/Powder',       w: 1.0, d: 2.1, category: 'bathroom' },
  { defId: 'laundry',         label: 'Laundry',         w: 1.8, d: 2.4, category: 'bathroom' },
  { defId: 'laundry_wc',      label: 'Laundry+WC',      w: 2.0, d: 2.4, category: 'bathroom' },
  // work
  { defId: 'studio_large',    label: 'Studio Large',    w: 4.5, d: 5.0, category: 'work' },
  { defId: 'studio_medium',   label: 'Studio Medium',   w: 4.0, d: 4.0, category: 'work' },
  { defId: 'studio_small',    label: 'Studio Small',    w: 3.0, d: 3.5, category: 'work' },
  { defId: 'office',          label: 'Office',          w: 3.0, d: 3.0, category: 'work' },
  { defId: 'study_nook',      label: 'Study Nook',      w: 1.5, d: 1.8, category: 'work' },
  // social
  { defId: 'living_dining',   label: 'Living/Dining',   w: 6.0, d: 5.0, category: 'social' },
  { defId: 'living',          label: 'Living',          w: 4.5, d: 4.5, category: 'social' },
  { defId: 'dining',          label: 'Dining',          w: 3.5, d: 3.8, category: 'social' },
  { defId: 'kitchen',         label: 'Kitchen',         w: 4.0, d: 3.2, category: 'social' },
  { defId: 'kitchen_island',  label: 'Kitchen+Island',  w: 4.5, d: 4.0, category: 'social' },
  { defId: 'butlers_pantry',  label: "Butler's Pantry", w: 1.8, d: 2.5, category: 'social' },
  { defId: 'theatre',         label: 'Theatre',         w: 4.0, d: 4.5, category: 'social' },
  { defId: 'library',         label: 'Library',         w: 3.0, d: 4.0, category: 'social' },
  // outdoor
  { defId: 'courtyard',       label: 'Courtyard',       w: 6.0, d: 5.5, category: 'outdoor' },
  { defId: 'courtyard_open',  label: 'Courtyard Open',  w: 5.0, d: 5.0, category: 'outdoor' },
  { defId: 'patio',           label: 'Patio',           w: 4.0, d: 3.5, category: 'outdoor' },
  { defId: 'deck',            label: 'Deck',            w: 4.0, d: 3.0, category: 'outdoor' },
  { defId: 'deck_raised',     label: 'Deck Raised',     w: 4.0, d: 3.0, category: 'outdoor' },
  { defId: 'terrace',         label: 'Terrace',         w: 5.0, d: 3.5, category: 'outdoor' },
  { defId: 'alfresco',        label: 'Alfresco',        w: 4.0, d: 3.0, category: 'outdoor' },
  { defId: 'pergola',         label: 'Pergola',         w: 4.0, d: 3.5, category: 'outdoor' },
  { defId: 'garden',          label: 'Garden',          w: 8.0, d: 6.0, category: 'outdoor' },
  { defId: 'garden_japanese', label: 'Japanese Garden', w: 4.0, d: 4.0, category: 'outdoor' },
  { defId: 'garden_walled',   label: 'Walled Garden',   w: 5.0, d: 5.0, category: 'outdoor' },
  { defId: 'pool',            label: 'Pool',            w: 3.0, d: 7.0, category: 'outdoor' },
  { defId: 'pool_lap',        label: 'Lap Pool',        w: 2.5, d: 9.0, category: 'outdoor' },
  { defId: 'pond',            label: 'Pond',            w: 2.0, d: 2.0, category: 'outdoor' },
  { defId: 'plunge_pool',     label: 'Plunge Pool',     w: 2.5, d: 3.5, category: 'outdoor' },
  { defId: 'dog_run',         label: 'Dog Run',         w: 2.0, d: 4.0, category: 'outdoor' },
  { defId: 'bbq_area',        label: 'BBQ Area',        w: 2.5, d: 2.5, category: 'outdoor' },
  { defId: 'fire_pit',        label: 'Fire Pit',        w: 3.0, d: 3.0, category: 'outdoor' },
  // transition
  { defId: 'entry_court',     label: 'Entry Court',     w: 3.5, d: 3.5, category: 'transition' },
  { defId: 'breezeway',       label: 'Breezeway',       w: 1.5, d: 3.0, category: 'transition' },
  { defId: 'loggia',          label: 'Loggia',          w: 2.0, d: 5.0, category: 'transition' },
  // circulation
  { defId: 'entry',           label: 'Entry',           w: 2.0, d: 2.5, category: 'circulation' },
  { defId: 'vestibule',       label: 'Vestibule',       w: 1.5, d: 1.8, category: 'circulation' },
  { defId: 'corridor',        label: 'Corridor',        w: 1.1, d: 4.0, category: 'circulation' },
  { defId: 'hallway',         label: 'Hallway',         w: 1.2, d: 3.0, category: 'circulation' },
  { defId: 'gallery',         label: 'Gallery',         w: 1.5, d: 5.0, category: 'circulation' },
  { defId: 'stair',           label: 'Stair',           w: 2.5, d: 3.5, category: 'circulation' },
  { defId: 'landing',         label: 'Landing',         w: 2.5, d: 2.5, category: 'circulation' },
  { defId: 'ramp',            label: 'Ramp',            w: 1.5, d: 4.0, category: 'circulation' },
  // service
  { defId: 'garage_single',   label: 'Garage Single',   w: 3.5, d: 6.0, category: 'service' },
  { defId: 'garage_double',   label: 'Garage Double',   w: 6.0, d: 6.0, category: 'service' },
  { defId: 'carport',         label: 'Carport',         w: 3.5, d: 5.5, category: 'service' },
  { defId: 'storage',         label: 'Storage',         w: 2.0, d: 2.5, category: 'service' },
  { defId: 'mud_room',        label: 'Mud Room',        w: 1.8, d: 2.0, category: 'service' },
  { defId: 'bin_store',       label: 'Bin Store',       w: 1.2, d: 1.5, category: 'service' },
  { defId: 'hot_water',       label: 'Hot Water',       w: 1.0, d: 1.5, category: 'service' },
  { defId: 'shed',            label: 'Shed',            w: 2.5, d: 3.0, category: 'service' },
  // furniture
  { defId: 'bed_king',          label: 'Bed King',        w: 1.93, d: 2.03, category: 'furniture' },
  { defId: 'bed_queen',         label: 'Bed Queen',       w: 1.53, d: 2.03, category: 'furniture' },
  { defId: 'bed_double',        label: 'Bed Double',      w: 1.38, d: 1.88, category: 'furniture' },
  { defId: 'bed_single',        label: 'Bed Single',      w: 0.92, d: 1.88, category: 'furniture' },
  { defId: 'sofa_3seat',        label: 'Sofa 3-seat',     w: 2.20, d: 0.90, category: 'furniture' },
  { defId: 'sofa_2seat',        label: 'Sofa 2-seat',     w: 1.60, d: 0.90, category: 'furniture' },
  { defId: 'armchair',          label: 'Armchair',        w: 0.85, d: 0.85, category: 'furniture' },
  { defId: 'coffee_table',      label: 'Coffee Table',    w: 1.20, d: 0.60, category: 'furniture' },
  { defId: 'tv_unit',           label: 'TV Unit',         w: 1.80, d: 0.45, category: 'furniture' },
  { defId: 'dining_table_6',    label: 'Dining Table 6',  w: 1.80, d: 0.90, category: 'furniture' },
  { defId: 'dining_table_4',    label: 'Dining Table 4',  w: 1.20, d: 0.80, category: 'furniture' },
  { defId: 'dining_chair',      label: 'Dining Chair',    w: 0.45, d: 0.45, category: 'furniture' },
  { defId: 'wardrobe_dbl',      label: 'Wardrobe Dbl',    w: 1.80, d: 0.60, category: 'furniture' },
  { defId: 'wardrobe_sgl',      label: 'Wardrobe Sgl',    w: 0.90, d: 0.60, category: 'furniture' },
  { defId: 'bookshelf',         label: 'Bookshelf',       w: 1.00, d: 0.30, category: 'furniture' },
  { defId: 'desk',              label: 'Desk',            w: 1.60, d: 0.75, category: 'furniture' },
  { defId: 'desk_l',            label: 'Desk L-shape',    w: 2.00, d: 1.60, category: 'furniture' },
  { defId: 'kitchen_bench',     label: 'Kitchen Bench',   w: 2.40, d: 0.60, category: 'furniture' },
  { defId: 'kitchen_island_f',  label: 'Kitchen Island',  w: 1.80, d: 0.90, category: 'furniture' },
  { defId: 'bath_freestanding', label: 'Bath Freestand',  w: 1.70, d: 0.80, category: 'furniture' },
  { defId: 'bath_builtin',      label: 'Bath Built-in',   w: 1.52, d: 0.76, category: 'furniture' },
  { defId: 'shower',            label: 'Shower',          w: 0.90, d: 0.90, category: 'furniture' },
  { defId: 'vanity_dbl',        label: 'Vanity Dbl',      w: 1.20, d: 0.55, category: 'furniture' },
  { defId: 'vanity_sgl',        label: 'Vanity Sgl',      w: 0.60, d: 0.55, category: 'furniture' },
  { defId: 'toilet',            label: 'Toilet',          w: 0.40, d: 0.72, category: 'furniture' },
  { defId: 'washer',            label: 'Washer',          w: 0.60, d: 0.60, category: 'furniture' },
  { defId: 'dryer',             label: 'Dryer',           w: 0.60, d: 0.60, category: 'furniture' },
  { defId: 'outdoor_table_6',   label: 'Outdoor Table 6', w: 1.80, d: 0.90, category: 'furniture' },
  { defId: 'outdoor_table_4',   label: 'Outdoor Table 4', w: 1.20, d: 0.80, category: 'furniture' },
  { defId: 'outdoor_lounge',    label: 'Outdoor Lounge',  w: 2.00, d: 0.90, category: 'furniture' },
  { defId: 'sunlounge',         label: 'Sun Lounge',      w: 0.70, d: 1.90, category: 'furniture' },
  { defId: 'bbq',               label: 'BBQ',             w: 1.20, d: 0.60, category: 'furniture' },
  { defId: 'pot_large',         label: 'Pot Large',       w: 0.60, d: 0.60, category: 'furniture' },
  { defId: 'pot_small',         label: 'Pot Small',       w: 0.40, d: 0.40, category: 'furniture' },
];

export const ROOM_DEFS = Object.fromEntries(defs.map(d => [d.defId, d]));

export const ROOM_GROUPS = [
  { id: 'sleeping',    label: 'Sleeping',    defs: defs.filter(d => d.category === 'sleeping') },
  { id: 'bathroom',    label: 'Bathroom',    defs: defs.filter(d => d.category === 'bathroom') },
  { id: 'work',        label: 'Work',        defs: defs.filter(d => d.category === 'work') },
  { id: 'social',      label: 'Social',      defs: defs.filter(d => d.category === 'social') },
  { id: 'outdoor',     label: 'Outdoor',     defs: defs.filter(d => d.category === 'outdoor') },
  { id: 'transition',  label: 'Transition',  defs: defs.filter(d => d.category === 'transition') },
  { id: 'circulation', label: 'Circulation', defs: defs.filter(d => d.category === 'circulation') },
  { id: 'service',     label: 'Service',     defs: defs.filter(d => d.category === 'service') },
  { id: 'furniture',   label: 'Furniture',   defs: defs.filter(d => d.category === 'furniture') },
];
